name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  firebase_auth: ^5.3.1
  shared_preferences: ^2.3.2
  

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
